module.exports = {
    FIELDS: [
      
      {
        name: "San Lorenzo",
        image:
          "https://i.pinimg.com/originals/2b/dd/d5/2bddd5f0ffb5cfae0d7191dc1a9b30a7.jpg",
        state: "APPROVED",
        price: 5200,
        address: "3585 Mount Tabor",
        openHour: '9:30',
        closeHour: '22:30',
        CityId: 4,
        SizeId: 3,
        SurfaceId: 3,
        score: 4.5,
        description: "Adquiriendo este servicio podrás disfrutar con 9 de tus mejores amigos o familiares de un muy buen partido de fútbol. Muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas de San Lorenzo.",
        OwnerId: 3
      },
      {
        name: "La hinchada FC",
        image:
          "https://civideportes.com.co/wp-content/uploads/2019/08/Cancha-de-f%C3%BAtbol-11.jpg",
        state: "APPROVED",
        price: 4800,
        address: "3585 Mount Tabor",
        openHour: '8:30',
        closeHour: '21:30',
        CityId: 1,
        SizeId: 2,
        SurfaceId: 1,
        score: 4.5,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
        OwnerId: 4
      },
      {
        name: "El predio (caballito)",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/el-predio-caballito-caba.jpeg?189654",
        state: "APPROVED",
        price: 6000,
        address: "Galicia 1973",
        openHour: '9:30',
        closeHour: '23:30',
        CityId: 2,
        SizeId: 2,
        SurfaceId: 2,
        score: 4,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
        OwnerId: 4
      },
      {
        name: "Asturiano Fútbol Club",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/asturiano-gba-norte.jpeg?357166",
        state: "APPROVED",
        price: 3800,
        address: "Carlos Francisco Melo 402 , GBA Norte",
        openHour: '9:00',
        closeHour: '23:00',
        CityId: 4,
        SizeId: 3,
        SurfaceId: 3,
        score: 3,
        description: "Adquiriendo este servicio podrás disfrutar con 9 de tus mejores amigos o familiares de un muy buen partido de fútbol. Muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas de Asturiano Fútbol Club.",
        OwnerId: 4
      },
      {
        name: "Federal 5",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/federal-5-caba.jpeg?607183",
        state: "APPROVED",
        price: 5000,
        address: "Bustamante 39, La Tablada, GBA Oeste",
        openHour: '9:00',
        closeHour: '23:00',
        CityId: 1,
        SizeId: 4,
        SurfaceId: 4,
        score: 5,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Federal 5 tiene para ti.",
        OwnerId: 5
      },
      {
        name: "Punto Gol",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/punto-gol-monte-grande.jpeg?401681",
        state: "APPROVED",
        price: 2900,
        address: "Fair 1360, Monte Grande , Capital Federal",
        openHour: '9:00',
        closeHour: '23:00',
        CityId: 2,
        SizeId: 4,
        SurfaceId: 3,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Punto Gol tiene para ti.",
        OwnerId: 5
      },
      {
        name: "Solis Cano II",
        image:
          "https://alquilatucancha.com/static/results/generic-sport-thumb.jpg",
        state: "APPROVED",
        price: 3200,
        address: "Santiago del Estero 1253 , Capital Federal",
        openHour: '9:00',
        closeHour: '23:00',
        CityId: 1,
        SizeId: 4,
        SurfaceId: 2,
        score: 3,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Solis Cano II tiene para ti.",
        OwnerId: 5
      },
      {
        name: "Ciudad (Ex-Muni)",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/ciudad-caba.jpeg?278270",
        state: "APPROVED",
        price: 7500,
        address: "Miguel B. Sanchez 1045 , Capital Federal",
        openHour: '9:00',
        closeHour: '23:00',
        CityId: 3,
        SizeId: 1,
        SurfaceId: 1,
        score: 4.5,
        description: "Ven y disfruta un divertido partido de fútbol 5 con tus amigos. Arma tu grupo de 10 amigos, alquila la cancha en la sede de tu preferencia y demuestra el campeón que llevas dentro. Ejercítate, pon a prueba tu resistencia física y hazle un golazo a la diversión. También podrás comprar el alquiler de balón para tu práctica.",
        OwnerId: 3,
        
      },
      {
        name: "Mi canchita",
        image:
          "https://www.parqueygrama.com/wp-content/uploads/2019/04/cancha-de-futbol.jpg",
        state: "APPROVED",
        price: 5000,
        address: "Santiago del Estero 1280 , Capital Federal",
        openHour: '8:00',
        closeHour: '23:00',
        CityId: 1,
        SizeId: 2,
        SurfaceId: 2,
        score: 4.5,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
        OwnerId: 3,
      },
      {
        name: "La bombonera",
        image:
          "https://www.citytowersgreen.com/images/amenidades/departamentos-en-preventa-con-cancha-de-futbol.jpg",
        state: "APPROVED",
        price: 7000,
        address: "4517 Gore Street, Capital Federal",
        openHour: '8:00',
        closeHour: '23:00',
        CityId: 1,
        SizeId: 3,
        SurfaceId: 2,
        score: 4.5,
        description: "Adquiriendo este servicio podrás disfrutar con 9 de tus mejores amigos o familiares de un muy buen partido de fútbol. Muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas de Asturiano Fútbol Club.",
        OwnerId: 4,
      },
      {
        name: 'Champions',
        image:
          "https://www.hoysejuega.com/uploads/Modules/ImagenesComplejos/800_600_show-gol-mendoza-canchas-de-futbol.jpg",
        state: "APPROVED",
        price: 6000,
        address: "Miguel B. Sanchez 1050, Capital Federal",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 1,
        SizeId: 4,
        SurfaceId: 2,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Champions tiene para ti.",
        OwnerId: 5,
      },
      {
        name: 'Lo de pablo',
        image: "https://imgar.zonapropcdn.com/avisos/resize/1/00/44/29/27/76/1200x1200/1724306414.jpg",
        state: "APPROVED",
        price: 6000,
        address: "2149 Worthington Drive, Cordoba",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 3,
        SizeId: 2,
        SurfaceId: 1,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Lo de pablo tiene para ti.",
        OwnerId: 3,
      },
      {
        name: "Canchas boulevar",
        image:
          "https://1.bp.blogspot.com/-f1_bvopRvbc/WC5vhWjbt5I/AAAAAAAA2kc/VFO4gW7mGMg6tqXibEMQG_qNiE3OrvqcgCLcB/s1600/1.jpg",
        state: "APPROVED",
        price: 3000,
        address: "3571 Gore Street",
        openHour: '9:30',
        closeHour: '23:00',
        CityId: 1,
        SizeId: 2,
        SurfaceId: 2,
        score: 4,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
        OwnerId: 3
      },
      {
        name: "Artear Futbol Club",
        image:
          "https://cloudfront-us-east-1.images.arcpublishing.com/artear/3KR4YMCTN6DIVP7MU53HO43CNE.jpg",
        state: "APPROVED",
        price: 4500,
        address: "726 Parkview Drive",
        openHour: '10:00',
        closeHour: '21:00',
        CityId: 3,
        SizeId: 1,
        SurfaceId: 4,
        score: 5,
        description:
          "Ven y disfruta un divertido partido de fútbol 5 con tus amigos. Arma tu grupo de 10 amigos, alquila la cancha en la sede de tu preferencia y demuestra el campeón que llevas dentro. Ejercítate, pon a prueba tu resistencia física y hazle un golazo a la diversión. También podrás comprar el alquiler de balón para tu práctica.",
        OwnerId: 3
      },
      {
        name: 'Calcho',
        image: "https://www.ledsolution.com.ar/documentos/1/5_reflectores-led-cancha-de-futbol.jpg",
        state: "APPROVED",
        price: 20000,
        address: "980 Thomas Street, Cordoba",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 2,
        SizeId: 3,
        SurfaceId:1,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Solis Calcho tiene para ti.",
        OwnerId: 4,
      },
      {
        name: 'La Calle Club',
        image: "https://i0.wp.com/lacalleclub.com/wp-content/uploads/2018/11/alquiler-cancha-futbol-la-calle-proximamente-1.jpg",
        state: "APPROVED",
        price: 18000,
        address: "1090 Marion Street, Cordoba",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 1,
        SizeId: 2,
        SurfaceId:3,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que La Calle Club tiene para ti.",
        OwnerId: 5,
      },
      {
        name: 'Futbol noble',
        image: "https://futbolnoble.com.ar/wp-content/uploads/2022/03/slide7_o.jpg",
        state: "APPROVED",
        price: 6540,
        address: "1090 Marion Street, Cordoba",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 4,
        SizeId: 3,
        SurfaceId:2,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que Futbol noble tiene para ti.",
        OwnerId: 4,
      },
      {
        name: 'LaSalle futbol',
        image: "https://media.vivieloeste.com.ar/adjuntos/320/migration/wp-content/uploads/2021/01/Container-canchas.jpg",
        state: "APPROVED",
        price: 7000,
        address: "3522 Spring Haven Trail, Capital Federal",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 4,
        SizeId: 3,
        SurfaceId:2,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que LaSalle futbol tiene para ti.",
        OwnerId: 4,
      },
      {
        name: 'La capital',
        image: "https://sport-12.com/wp-content/uploads/2022/02/Cancha-Chapultepec_cuadrado.jpg",
        state: "APPROVED",
        price: 8000,
        address: "1391 Pennsylvania Avenue, Capital Federal",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 3,
        SizeId: 2,
        SurfaceId:1,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que La capital tiene para ti.",
        OwnerId: 3,
      },
      {
        name: 'La hinchada',
        image: "https://ccmetropolis.com.co/wp-content/uploads/2020/12/IMG_2314-e1607608227865.jpg",
        state: "APPROVED",
        price: 4000,
        address: "4956 Rockford Mountain Lane, Capital Federal",
        openHour: '8:00',
        closeHour: '20:00',
        CityId: 4,
        SizeId: 1,
        SurfaceId:2,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas que La hinchada tiene para ti.",
        OwnerId: 4,
      },
    ],

  };