module.exports = {
  FIELDS: [
    {
      name: "River",
      image:
        "https://i.pinimg.com/originals/1f/54/50/1f5450f4346e2e58eff217eecbfd73f1.png",
      state: "APPROVED",
      price: 3000,
      address: "3571 Gore Street",
      openHour: 9,
      closeHour: 23,
      CityId: 1,
      SizeId: 2,
      SurfaceId: 2,
      score: 4,
      description: "aqui va la decription",
    },
    {
      name: "Boca",
      image:
        "https://i.pinimg.com/550x/c9/10/51/c91051177eb678932c82bf31ed6bbcdd.jpg",
      state: "APPROVED",
      price: 4500,
      address: "726 Parkview Drive",
      openHour: 10,
      closeHour: 21,
      CityId: 3,
      SizeId: 1,
      SurfaceId: 4,
      score: 5,
      description: "aqui va la decription",
    },
    {
      name: "San Lorenzo",
      image:
        "https://i.pinimg.com/originals/2b/dd/d5/2bddd5f0ffb5cfae0d7191dc1a9b30a7.jpg",
      state: "APPROVED",
      price: 5200,
      address: "3585 Mount Tabor",
      openHour: 9,
      closeHour: 22,
      CityId: 4,
      SizeId: 3,
      SurfaceId: 3,
      score: 4.5,
      description: "aqui va la decription",
    },
    {
      name: "La hinchada FC",
      image:
        "https://civideportes.com.co/wp-content/uploads/2019/08/Cancha-de-f%C3%BAtbol-11.jpg",
      state: "APPROVED",
      price: 4800,
      address: "3585 Mount Tabor",
      openHour: 8,
      closeHour: 21,
      CityId: 1,
      SizeId: 3,
      SurfaceId: 1,
      score: 4.5,
      description: "aqui va la decription",
    },
    {
      name: "El predio (caballito)",
      image:
        "https://alquilatucancha.com/uploads/clubs/bg/el-predio-caballito-caba.jpeg?189654",
      state: "APPROVED",
      price: 6000,
      address: "Galicia 1973",
      openHour: 9,
      closeHour: 23,
      CityId: 2,
      SizeId: 3,
      SurfaceId: 2,
      score: 4,
      description: "aqui va la decription",
    },
    {
      name: "Asturiano Fútbol Club",
      image:
        "https://alquilatucancha.com/uploads/clubs/bg/asturiano-gba-norte.jpeg?357166",
      state: "APPROVED",
      price: 3800,
      address: "Carlos Francisco Melo 402 , GBA Norte",
      openHour: 9,
      closeHour: 23,
      CityId: 4,
      SizeId: 3,
      SurfaceId: 3,
      score: 3,
      description: "aqui va la decription",
    },
    {
      name: "Federal 5",
      image:
        "https://alquilatucancha.com/uploads/clubs/bg/federal-5-caba.jpeg?607183",
      state: "APPROVED",
      price: 5000,
      address: "Bustamante 39, La Tablada , GBA Oeste",
      openHour: 9,
      closeHour: 23,
      CityId: 1,
      SizeId: 4,
      SurfaceId: 4,
      score: 5,
      description: "aqui va la decription",
    },
    {
      name: "Punto Gol",
      image:
        "https://alquilatucancha.com/uploads/clubs/bg/punto-gol-monte-grande.jpeg?401681",
      state: "APPROVED",
      price: 2900,
      address: "Fair 1360, Monte Grande , Capital Federal",
      openHour: 9,
      closeHour: 23,
      CityId: 2,
      SizeId: 4,
      SurfaceId: 3,
      score: 4,
      description: "aqui va la decription",
    },
    {
      name: "Solis Cano II",
      image:
        "https://alquilatucancha.com/static/results/generic-sport-thumb.jpg",
      state: "APPROVED",
      price: 3200,
      address: "Santiago del Estero 1253 , Capital Federal",
      openHour: 9,
      closeHour: 23,
      CityId: 1,
      SizeId: 4,
      SurfaceId: 2,
      score: 3,
      description: "aqui va la decription",
    },
    {
      name: "Ciudad (Ex-Muni)",
      image:
        "https://alquilatucancha.com/uploads/clubs/bg/ciudad-caba.jpeg?278270",
      state: "APPROVED",
      price: 7500,
      address: "Miguel B. Sanchez 1045 , Capital Federal",
      openHour: 9,
      closeHour: 23,
      CityId: 3,
      SizeId: 3,
      SurfaceId: 1,
      score: 4.5,
      description: "aqui va la decription",
    },
  ],
};
