module.exports = {
    FIELDS: [
      {
        name: "River",
        image:
          "https://i.pinimg.com/originals/1f/54/50/1f5450f4346e2e58eff217eecbfd73f1.png",
        state: "APPROVED",
        price: 3000,
        address: "3571 Gore Street",
        openHour: 9,
        closeHour: 23,
        CityId: 1,
        SizeId: 2,
        SurfaceId: 2,
        score: 4,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
      },
      {
        name: "Boca",
        image:
          "https://i.pinimg.com/550x/c9/10/51/c91051177eb678932c82bf31ed6bbcdd.jpg",
        state: "APPROVED",
        price: 4500,
        address: "726 Parkview Drive",
        openHour: 10,
        closeHour: 21,
        CityId: 3,
        SizeId: 1,
        SurfaceId: 4,
        score: 5,
        description:
          "Ven y disfruta un divertido partido de fútbol 5 con tus amigos. Arma tu grupo de 10 amigos, alquila la cancha en la sede de tu preferencia y demuestra el campeón que llevas dentro. Ejercítate, pon a prueba tu resistencia física y hazle un golazo a la diversión. También podrás comprar el alquiler de balón para tu práctica.",
      },
      {
        name: "San Lorenzo",
        image:
          "https://i.pinimg.com/originals/2b/dd/d5/2bddd5f0ffb5cfae0d7191dc1a9b30a7.jpg",
        state: "APPROVED",
        price: 5200,
        address: "3585 Mount Tabor",
        openHour: 9,
        closeHour: 22,
        CityId: 4,
        SizeId: 3,
        SurfaceId: 3,
        score: 4.5,
        description: "Adquiriendo este servicio podrás disfrutar con 9 de tus mejores amigos o familiares de un muy buen partido de fútbol. Muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas de San Lorenzo.",
      },
      {
        name: "La hinchada FC",
        image:
          "https://civideportes.com.co/wp-content/uploads/2019/08/Cancha-de-f%C3%BAtbol-11.jpg",
        state: "APPROVED",
        price: 4800,
        address: "3585 Mount Tabor",
        openHour: 8,
        closeHour: 21,
        CityId: 1,
        SizeId: 2,
        SurfaceId: 1,
        score: 4.5,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
      },
      {
        name: "El predio (caballito)",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/el-predio-caballito-caba.jpeg?189654",
        state: "APPROVED",
        price: 6000,
        address: "Galicia 1973",
        openHour: 9,
        closeHour: 23,
        CityId: 2,
        SizeId: 2,
        SurfaceId: 2,
        score: 4,
        description: "Disfruta de una hora de juego en nuestras canchas de fútbol 7, reúne a otros 6 amigos y pon en prácticas todas tus habilidades en este deporte. También podrás comprar el alquiler de balón para tu práctica.",
      },
      {
        name: "Asturiano Fútbol Club",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/asturiano-gba-norte.jpeg?357166",
        state: "APPROVED",
        price: 3800,
        address: "Carlos Francisco Melo 402 , GBA Norte",
        openHour: 9,
        closeHour: 23,
        CityId: 4,
        SizeId: 3,
        SurfaceId: 3,
        score: 3,
        description: "Adquiriendo este servicio podrás disfrutar con 9 de tus mejores amigos o familiares de un muy buen partido de fútbol. Muestra todas tus habilidades en este deporte y siéntete como todo un jugador profesional en las canchas de Asturiano Fútbol Club.",
      },
      {
        name: "Federal 5",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/federal-5-caba.jpeg?607183",
        state: "APPROVED",
        price: 5000,
        address: "Bustamante 39, La Tablada , GBA Oeste",
        openHour: 9,
        closeHour: 23,
        CityId: 1,
        SizeId: 4,
        SurfaceId: 4,
        score: 5,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador prefesional en las canchas que Federal 5 tiene para ti.",
      },
      {
        name: "Punto Gol",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/punto-gol-monte-grande.jpeg?401681",
        state: "APPROVED",
        price: 2900,
        address: "Fair 1360, Monte Grande , Capital Federal",
        openHour: 9,
        closeHour: 23,
        CityId: 2,
        SizeId: 4,
        SurfaceId: 3,
        score: 4,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador prefesional en las canchas que Punto Gol tiene para ti.",
      },
      {
        name: "Solis Cano II",
        image:
          "https://alquilatucancha.com/static/results/generic-sport-thumb.jpg",
        state: "APPROVED",
        price: 3200,
        address: "Santiago del Estero 1253 , Capital Federal",
        openHour: 9,
        closeHour: 23,
        CityId: 1,
        SizeId: 4,
        SurfaceId: 2,
        score: 3,
        description: "Disfruta de un muy buen partido de fútbol 11 con tus mejores amigos o familiares, muestra todas tus habilidades en este deporte y siéntete como todo un jugador prefesional en las canchas que Solis Cano II tiene para ti.",
      },
      {
        name: "Ciudad (Ex-Muni)",
        image:
          "https://alquilatucancha.com/uploads/clubs/bg/ciudad-caba.jpeg?278270",
        state: "APPROVED",
        price: 7500,
        address: "Miguel B. Sanchez 1045 , Capital Federal",
        openHour: 9,
        closeHour: 23,
        CityId: 3,
        SizeId: 1,
        SurfaceId: 1,
        score: 4.5,
        description: "Ven y disfruta un divertido partido de fútbol 5 con tus amigos. Arma tu grupo de 10 amigos, alquila la cancha en la sede de tu preferencia y demuestra el campeón que llevas dentro. Ejercítate, pon a prueba tu resistencia física y hazle un golazo a la diversión. También podrás comprar el alquiler de balón para tu práctica.",
      },
    ],
  };